### ISSUE TITLE
Webpack Error

### ISSUE THREAD

**Issue by skarampatakis** [okgreece/the-accountant#1]
When run ```make run``` I get the following error. It happens only the ```feature/analytics``` branch. 

```error Expected linebreaks to be 'LF' but found 'CRLF' linebreak-style ```

A possible temporary workaround would be 

https://stackoverflow.com/questions/37826449/expected-linebreaks-to-be-lf-but-found-crlf-linebreak-style-in-eslint-using

but perhaps changing line endings is preferable.

**Comment by skarampatakis** [comment]
@larjohn I found out that this is an addition of this branch. Is it needed? Could we safely remove it completely?

**Comment by larjohn** [comment]
I was building on Windows and fixing the line endings didn't work. I had no
more time to investigate so I chose to go on with the setting. If you have
tried and it builds on Windows without it (because it is a pitty not to
just because of line endings), then you can remove the setting.




*ʌἁɀɑƿѻѕ ɪɷɑⱴⱴἱɗʜѕ*

2017-07-16 8:35 GMT+03:00 Sotirios Karampatakis <notifications@github.com>:

**Comment by skarampatakis** [comment]
I am building on unix and that setting caused the build failure. I changed the configuration to "unix" and it worked so I guess this should be the default. However the configuration needed should be either documented or configurable automatically on build by env variables. 

By the way was this caused by your git settings? I had a similar problem once and found that was caused by how git pushes my files. On win systems you can choose to keep your local repo on CRLF but push with LF. on the remote repo.

**Comment by larjohn** [comment]
Yes most of the times it's how you installed git. It's weird though,
because it was just one offending file and it seemed impossible to fix.




*ʌἁɀɑƿѻѕ ɪɷɑⱴⱴἱɗʜѕ*

2017-07-16 10:50 GMT+03:00 Sotirios Karampatakis <notifications@github.com>:

**Comment by skarampatakis** [comment]
Do you recall which one it was?

**Comment by larjohn** [comment]
It must have been modernizr.conf.js
